notifications:
email: false
language: python
python: stable
script:
- errors=`find . -name "*.py" -exec flake8 --max-line-length=120 \;` 
- |
    if [ -z "$errors" ]; then
        true
    else
        echo "$errors"
        false
    fi
